package Assets.Scripts;

public class Script {
    public static final String[] storyTexts = {
        "<html><b>BOOTING UP.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The sound of rapid typing fills the air, accompanied by the soft hum of a laptop.</i></html>",
        "<html><i>The sound of typing continues. A soft click as Elara presses a key.</i></html>",
        "<html><i>The screen flickers, showing an error message:</i></html>",
        "<html><span style=color'red;'>Compilation Failed.</span></html>",
        "I should probably get some sleep... but this stupid code...",
        "<html><i>She sighs, staring at the screen.</i></html>",
        "<html><i>The error message glitches and changes to:</i></html>",
        "<html><span style=color'red;'>Do you want to debug your life? [Y/N]</span></html>",
        "What?",
        "<html><i>She stares at the screen for a moment, unsure.</i></html>",
        "<html><i>Her finger hovers over the keyboard.</i></html>",
        "This is probably just some weird joke.",
        "<html><i>She presses Y.</i></html>",
        "<html><i>The screen flickers violently. The hum of the laptop grows louder, and the room around her begins to distort.</i></html>",
        "Whoa, what the-?",
        "<html><i>The screen goes black for a moment.</i></html>",
        "<html><i>When it returns, the room is gone.</i></html>",
        "<html><i>Elara finds herself in a strange, glowing space filled with floating lines of code and distorted light.</i></html>",
        "Okay, this isn’t normal. Where am I?",
        "<html><i>A small, glowing figure appears in front of her, zipping around excitedly.</i></html>",
        "<html><span style=color:'yellow;'>Oh, finally! Someone’s here!</span></html>",
        "What the-? Who are you?",
        "<html><span style=color:'yellow;'>I’m Byte! Welcome to Nullspace!</span></html>",
        "Nullspace?",
        "What is this place? How did I get here?",
        "<html><span style=color:'yellow;'>You’re here to fix things, obviously. You’re the one who clicked “Yes,” right?</span></html>",
        "Fix what? I don’t even know where “here” is.",
        "<html><span style=color:'yellow;'>You’re in Nullspace, dummy. It’s all messed up, and you’ve gotta help fix it.</span></html>",
        "<html><i>This is insane. I must be dreaming.</i></html>",
        "<html><i>She looks around at the strange, glitching environment.</i></html>",
        "Okay, fine. What do I have to do?",
        "<html><span style=color:'yellow;'>Well, first, you’ve got to figure out how to get back to the real world.</span></html>",
        "<html><span style=color:'yellow;'>But that’s gonna take more than just fixing bugs.</span></html>",
        "<html><span style=color:'yellow;'>You’ll need to fix... well, you...</span></html>",
        "Great. Just what I needed.",
        "",
        "<html><b>THE FIRST GLITCH.</b></html>",
        "<html><i>Black screen.<i/></html>",
        "<html><i>A soft, steady breath from Elara fills the silence.</i></html>",
        "Okay, Elara, pull yourself together. This is just... some weird glitch in the matrix.",
        "<html><i>A soft buzzing sound fills the air. Elara blinks, and the scene shifts to reveal a fractured, digital world.<i/></html>",
        "This is not a dream. This is... definitely not a dream.",
        "<html><i>Lines of code float in the air like constellations.</i></html>",
        "<html><i>The ground beneath her is unstable, flickering between solid and transparent.</i></html>",
        "<html><span style=color:'yellow;'>You’re getting the hang of it!</span></html>",
        "Jeez! Don’t sneak up on me like that!",
        "<html><span style=color:'yellow;'>Sorry, I get excited. Anyway, welcome to the first level of Nullspace.</span><html>",
        "<html><span style=color:'yellow;'>This place is full of glitches, and you’re gonna have to clean them up.</span></html>",
        "Glitches? What do you mean?",
        "<html><span style=color:'yellow;'>See that over there?</span></html>",
        "<html><i>Byte points to a nearby structure that’s glitching in and out of existence, flickering between code and broken pixels.</i></html>",
        "Yeah, I see it. What is it?",
        "<html><span style=color:'yellow;'>That’s a Memory Glitch. It’s a part of you, something you’ve been avoiding.</span></html>",
        "<html><span style=color:'yellow;'>Fix it, and maybe you’ll start to understand this whole mess..</span></html>",
        "Avoiding? What does that even mean?",
        "<html><i>Elara walks toward the glitching structure.</i></html>",
        "<html><i>As she gets closer, the glitch intensifies, and distorted memories begin to flood her mind; flashes of a heated argument with Raina, her best friend, who she hasn’t spoken to in months.</i></html>",
        "I... I haven’t thought about this in so long.",
        "<html><i>The glitch pulses.</i></html>",
        "<html><i>A voice echoes in her mind, faint but clear.</i></html>",
        "<html><span style=color'red;'>Why are you always shutting me out, Elara?</span></html>",
        "<html><span style=color'red;'>I’m here, you know... but you never seem to care anymore.</span></html>",
        "I... I didn’t mean to...",
        "<html><i>The glitch intensifies, and Elara reaches out, touching it.</i></html>",
        "<html><i>The distortion stops, and the glitch begins to stabilize, revealing a clear image of Raina’s face, frozen in time.</i></html>",
        "<html><i>But it’s not just her face; it’s the way she looked the last time they spoke, hurt and confused.</i></html>",
        "That night... I should’ve said something.",
        "<html><i>The memory of that night floods back; her avoiding Raina’s calls, brushing off her concerns, telling herself that it was easier to just let things fade away.</i></html>",
        "I thought if I just kept going, kept busy, it would all fix itself.",
        "But it didn’t.",
        "<html><i>She stares at the image of Raina, the weight of regret heavy in her chest.</i></html>",
        "<html><span style=color:'yellow;'>You did it. You fixed the glitch.</span></html>",
        "<html><span style=color:'yellow;'>But it’s not over.</span></html>",
        "That was... real.",
        "I didn’t even realize how much I’ve been avoiding it.",
        "<html><span style=color:'yellow;'>It’s all connected.</span></html>",
        "<html><span style=color:'yellow;'>The glitches aren’t just in the system; they’re in you.</span></html>",
        "I’ve been running from this for so long...",
        "<html><span style=color:'yellow;'>You can’t fix the system without fixing yourself. But don’t worry, we’ll figure it out together.</span></html>",
        "<html><i>Elara takes a deep breath, looking at the now-stable image of Raina.</i></html>",
        "I don’t know what this place is or why I’m here.",
        "But maybe... maybe I’ve been avoiding more than just bugs.",
        "",
        "<html><b>THE SECOND GLITCH.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The soft hum of the laptop fills the silence.</i></html>",
        "<html><i>Elara’s breathing slows, the weight of her thoughts pressing in.</i></html>",
        "I thought I was too busy to care. Too busy to notice.",
        "But... maybe I wasn’t as busy as I thought.",
        "Maybe I was just... avoiding everything that made me uncomfortable.",
        "<html><i>The screen flickers, and the next glitch appears; a soft, glowing figure in the distance.</i></html>",
        "<html><i>It looks familiar, but Elara can’t quite place it.</i></html>",
        "<html><i>She walks toward it, the glitch growing clearer with each step.</i></html>",
        "This one... feels different. It’s not like the others.",
        "<html><i>As Elara gets closer, the glitch clears up, revealing an image of an older woman; her grandmother, sitting in a cozy chair by a window, knitting a scarf.</i></html>",
        "<html><i>The image is warm, soft, almost like a memory Elara had forgotten.</i></html>",
        "Grandma...?",
        "<html><i>The image flickers again, and Elara sees a memory play out.</i></html>",
        "<html><i>Her grandmother is sitting at the kitchen table, a gentle smile on her face, while Elara, much younger, rolls her eyes and sighs as her grandmother insists on packing her lunch for school.</i></html>",
        "<html><span style=color'red;'>You’re going to need something to eat, Elara. You can’t skip meals, sweetheart.</span></html>",
        "<html><span style=color'red;'>I’m fine, Grandma. I’m not a kid anymore. I can handle it.</span></html>",
        "<html><i>The memory shifts to another moment; her grandmother fussing over Elara’s jacket on a cold winter day, adjusting the collar, making sure it’s zipped up all the way.</i></html>",
        "<html><span style=color'red;'>Make sure you stay warm, dear. You don’t want to catch a cold.</span></html>",
        "<html><span style=color'red;'>I’m fine! Stop treating me like a baby.</span></html>",
        "<html><i>The image of her grandmother flickers again, and Elara’s heart sinks.</i></html>",
        "<html><i>She remembers the last time they spoke, the last time she saw her; just before her grandmother passed away.</i></html>",
        "I never told her how much I appreciated her. How much I needed her.",
        "<html><i>The image shifts again, showing her grandmother lying in her bed, frail and weak.</i></html>",
        "<html><i>Elara is standing by her arm, arms crossed, unable to face her.</i></html>",
        "<html><span style=color'red;'>Don’t be mad at me, Elara. I only wanted to see you succeed... to make sure you will be okay.</span></html>",
        "<html><i>Elara’s younger self just stands there, silent, unable to speak the words she should have said.</i></html>",
        "<html><i>The memory fades, and the glitch stabilizes, leaving Elara staring at her grandmother’s warm, loving face.</i></html>",
        "I didn’t know.",
        "I didn’t understand how much she loved me.",
        "How much she just wanted to keep me safe...",
        "<html><i>She closes her eyes, a tear slipping down her cheek.</i></html>",
        "I resented her for trying to protect me... for caring too much.",
        "But now... now I’d give anything to go back.",
        "To tell her I understood. To thank her.",
        "<html><i>The glitch flickers one last time, and the image of her grandmother disappears, leaving Elara standing alone in the quiet, digital space.</i></html>",
        "<html><span style=color:'yellow;'>You fixed another one. But this one... this one’s a little harder, huh?</span></html>",
        "Yeah. I didn’t even realize... how much I took for granted.",
        "<html><span style=color:'yellow;'>It’s not easy. But you’re getting there.</span></html>",
        "I always thought I had time.",
        "But time... time doesn’t wait for anyone.",
        "",
    };
}
