package Assets.Scripts;

public class ScriptRaw {
    public static final String[] storyTexts = {
        "BOOTING UP.",
        "Black screen.",
        "The sound of rapid typing fills the air, accompanied by the soft hum of a laptop.",
        "The sound of typing continues. A soft click as Elara presses a key.",
        "The screen flickers, showing an error message:",
        "Compilation Failed.",
        "I should probably get some sleep... but this stupid code...",
        "She sighs, staring at the screen.",
        "The error message glitches and changes to:",
        "Do you want to debug your life? [Y/N]",
        "What?",
        "She stares at the screen for a moment, unsure.",
        "Her finger hovers over the keyboard.",
        "This is probably just some weird joke.",
        "She presses Y.",
        "The screen flickers violently. The hum of the laptop grows louder, and the room around her begins to distort.",
        "Whoa, what the-?",
        "The screen goes black for a moment.",
        "When it returns, the room is gone.",
        "Elara finds herself in a strange, glowing space filled with floating lines of code and distorted light.",
        "Okay, this isn’t normal. Where am I?",
        "A small, glowing figure appears in front of her, zipping around excitedly.",
        "Oh, finally! Someone’s here!",
        "What the-? Who are you?",
        "I’m Byte! Welcome to Nullspace!",
        "Nullspace?",
        "What is this place? How did I get here?",
        "You’re here to fix things, obviously. You’re the one who clicked “Yes,” right?",
        "Fix what? I don’t even know where “here” is.",
        "You’re in Nullspace, dummy. It’s all messed up, and you’ve gotta help fix it.",
        "This is insane. I must be dreaming.",
        "She looks around at the strange, glitching environment.",
        "Okay, fine. What do I have to do?",
        "Well, first, you’ve got to figure out how to get back to the real world.",
        "But that’s gonna take more than just fixing bugs.",
        "You’ll need to fix... well, you...",
        "Great. Just what I needed.",
        "",
        "THE FIRST GLITCH.",
        "Black screen.",
        "A soft, steady breath from Elara fills the silence.",
        "Okay, Elara, pull yourself together. This is just... some weird glitch in the matrix.",
        "A soft buzzing sound fills the air. Elara blinks, and the scene shifts to reveal a fractured, digital world.",
        "This is not a dream. This is... definitely not a dream.",
        "Lines of code float in the air like constellations.",
        "The ground beneath her is unstable, flickering between solid and transparent.",
        "You’re getting the hang of it!",
        "Jeez! Don’t sneak up on me like that!",
        "Sorry, I get excited. Anyway, welcome to the first level of Nullspace.",
        "This place is full of glitches, and you’re gonna have to clean them up.",
        "Glitches? What do you mean?",
        "See that over there?",
        "Byte points to a nearby structure that’s glitching in and out of existence, flickering between code and broken pixels.",
        "Yeah, I see it. What is it?",
        "That’s a Memory Glitch. It’s a part of you, something you’ve been avoiding.",
        "Fix it, and maybe you’ll start to understand this whole mess..",
        "Avoiding? What does that even mean?",
        "Elara walks toward the glitching structure.",
        "As she gets closer, the glitch intensifies, and distorted memories begin to flood her mind; flashes of a heated argument with Raina, her best friend, who she hasn’t spoken to in months.",
        "I... I haven’t thought about this in so long.",
        "The glitch pulses.",
        "A voice echoes in her mind, faint but clear.",
        "Why are you always shutting me out, Elara?",
        "I’m here, you know... but you never seem to care anymore.",
        "I... I didn’t mean to...",
        "The glitch intensifies, and Elara reaches out, touching it.",
        "The distortion stops, and the glitch begins to stabilize, revealing a clear image of Raina’s face, frozen in time.",
        "But it’s not just her face; it’s the way she looked the last time they spoke, hurt and confused.",
        "That night... I should’ve said something.",
        "The memory of that night floods back; her avoiding Raina’s calls, brushing off her concerns, telling herself that it was easier to just let things fade away.",
        "I thought if I just kept going, kept busy, it would all fix itself.",
        "But it didn’t.",
        "She stares at the image of Raina, the weight of regret heavy in her chest.",
        "You did it. You fixed the glitch.",
        "But it’s not over.",
        "That was... real.",
        "I didn’t even realize how much I’ve been avoiding it.",
        "It’s all connected.",
        "The glitches aren’t just in the system; they’re in you.",
        "I’ve been running from this for so long...",
        "You can’t fix the system without fixing yourself. But don’t worry, we’ll figure it out together.",
        "Elara takes a deep breath, looking at the now-stable image of Raina.",
        "I don’t know what this place is or why I’m here.",
        "But maybe... maybe I’ve been avoiding more than just bugs.",
        "",
        "THE SECOND GLITCH.",
        "Black screen.",
        "The soft hum of the laptop fills the silence.",
        "Elara’s breathing slows, the weight of her thoughts pressing in.",
        "I thought I was too busy to care. Too busy to notice.",
        "But... maybe I wasn’t as busy as I thought.",
        "Maybe I was just... avoiding everything that made me uncomfortable.",
        "The screen flickers, and the next glitch appears; a soft, glowing figure in the distance.",
        "It looks familiar, but Elara can’t quite place it.",
        "She walks toward it, the glitch growing clearer with each step.",
        "This one... feels different. It’s not like the others.",
        "As Elara gets closer, the glitch clears up, revealing an image of an older woman; her grandmother, sitting in a cozy chair by a window, knitting a scarf.",
        "The image is warm, soft, almost like a memory Elara had forgotten.",
        "Grandma...?",
        "The image flickers again, and Elara sees a memory play out.",
        "Her grandmother is sitting at the kitchen table, a gentle smile on her face, while Elara, much younger, rolls her eyes and sighs as her grandmother insists on packing her lunch for school.",
        "You’re going to need something to eat, Elara. You can’t skip meals, sweetheart.",
        "I’m fine, Grandma. I’m not a kid anymore. I can handle it.",
        "The memory shifts to another moment; her grandmother fussing over Elara’s jacket on a cold winter day, adjusting the collar, making sure it’s zipped up all the way.",
        "Make sure you stay warm, dear. You don’t want to catch a cold.",
        "I’m fine! Stop treating me like a baby.",
        "The image of her grandmother flickers again, and Elara’s heart sinks.",
        "She remembers the last time they spoke, the last time she saw her; just before her grandmother passed away.",
        "I never told her how much I appreciated her. How much I needed her.",
        "The image shifts again, showing her grandmother lying in her bed, frail and weak.",
        "Elara is standing by her arm, arms crossed, unable to face her.",
        "Don’t be mad at me, Elara. I only wanted to see you succeed... to make sure you will be okay.",
        "Elara’s younger self just stands there, silent, unable to speak the words she should have said.",
        "The memory fades, and the glitch stabilizes, leaving Elara staring at her grandmother’s warm, loving face.",
        "I didn’t know.",
        "I didn’t understand how much she loved me.",
        "How much she just wanted to keep me safe...",
        "She closes her eyes, a tear slipping down her cheek.",
        "I resented her for trying to protect me... for caring too much.",
        "But now... now I’d give anything to go back.",
        "To tell her I understood. To thank her.",
        "The glitch flickers one last time, and the image of her grandmother disappears, leaving Elara standing alone in the quiet, digital space.",
        "You fixed another one. But this one... this one’s a little harder, huh?",
        "Yeah. I didn’t even realize... how much I took for granted.",
        "It’s not easy. But you’re getting there.",
        "I always thought I had time.",
        "But time... time doesn’t wait for anyone.",
        "",
        "THE THIRD GLITCH",
        "Black screen.",
        "The faint hum of the laptop continues, accompanied by the rhythmic ticking of a clock.",
        "Elara’s gaze drifts to the corner of the screen, where a new glitch begins to form; a swirling, fragmented map of the world.",
        "This one feels... bigger.",
        "Like it’s pulling me somewhere far away.",
        "The glitch stabilizes, and Elara finds herself standing in a grand hall.",
        "The walls are lined with flags from different countries, their colors vibrant and striking.",
        "At the center of the room is a podium, a microphone, and an empty chair.",
        "The air feels heavy with expectation.",
        "I know this place. It’s not real, but... it’s familiar.",
        "As she steps closer to the podium, the scene shifts.",
        "Suddenly, she’s younger, sitting at her childhood desk, surrounded by stacks of books and a world map pinned to the wall.",
        "She’s practicing a speech in front of a mirror, her voice shaky but determined.",
        "Good evening, esteemed delegates.",
        "Today, we gather to discuss a matter of global importance...",
        "The memory flickers, and the younger Elara looks up, her eyes shining with ambition.",
        "One day, I’ll be there. I’ll make a difference.",
        "The scene shifts again.",
        "Now, Elara is older, sitting in a college lecture hall.",
        "She’s scribbling notes furiously, her passion still burning bright.",
        "But the memory grows hazy, and the scene changes once more; this time, to a dimly lit room where Elara sits in front of her laptop, staring at a blank application form for a diplomatic internship.",
        "I remember this. I couldn’t even fill out the first question",
        "The younger Elara in the memory hesitates, her fingers hovering over the keyboard.",
        "She looks frustrated, then closes the laptop with a sigh.",
        "Maybe I’m not good enough.",
        "The scene fades, leaving Elara standing alone in the grand hall again.",
        "The flags now look faded, the podium dusty and forgotten.",
        "I told myself it was just a silly dream.",
        "That I wasn’t smart enough, brave enough...",
        "But was it really about that? Or was I just scared?",
        "A voice echoes softly in the hall; it’s her own, but older, more worn.",
        "You gave up before you even tried.",
        "Elara flinches, the words hitting her like a punch to the gut.",
        "She looks up at the empty chair by the podium, imagining herself sitting there, speaking to the world.",
        "I wanted to be someone who mattered. Someone who could change things.",
        "But instead, I stayed in my bubble, too afraid to fail.",
        "She takes a deep breath, her hands trembling.",
        "It’s not too late. It can’t be.",
        "The glitch begins to fade, the map reassembling itself into a complete image.",
        " Elara reaches out, touching it gently.",
        "That one hit a nerve, huh?",
        "Yeah. I guess I forgot how much I wanted it... how much it meant to me.",
        "Forgotten doesn’t mean gone.",
        "Maybe I don’t have to give up.",
        "Maybe... it’s time to try again.",
        "",
    };
}
