package Assets.Scripts; public class Script { public static final String[] storyTexts = { "<html><b span style=color:#ed4337;>SYSTEM BOOT.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The sound of rapid typing fills the air, accompanied by the soft hum of a laptop.</i></html>",
        "<html><i>The sound of typing continues. A soft click as Elara presses a key.</i></html>",
        "<html><i>The screen flickers, showing an error message:</i></html>",
        "<html><b span style=color:'red';>Compilation Failed.</b></html>",
        "I should probably get some sleep... but this stupid code...",
        "<html><i>She sighs, staring at the screen.</i></html>",
        "<html><i>The error message glitches and changes to:</i></html>",
        "<html><b span style=color:'red';>Do you want to debug your life? [Y/N]</span></html>",
        "What?",
        "<html><i>She stares at the screen for a moment, unsure.</i></html>",
        "<html><i>Her finger hovers over the keyboard.</i></html>",
        "This is probably just some weird joke.",
        "<html><i>She presses Y.</i></html>",
        "<html><i>The screen flickers violently. The hum of the laptop grows louder, and the room around her begins to distort.</i></html>",
        "Whoa, what the-?",
        "<html><i>The screen goes black for a moment.</i></html>",
        "<html><i>When it returns, the room is gone.</i></html>",
        "<html><i>Elara finds herself in a strange, glowing space filled with floating lines of code and distorted light.</i></html>",
        "Okay, this isn’t normal. Where am I?",
        "<html><i>A small, glowing figure appears in front of her, zipping around excitedly.</i></html>",
        "<html><span style=color:'yellow';>Oh, finally! Someone’s here!</span></html>",
        "What the-? Who are you?",
        "<html><span style=color:'yellow';>I’m Byte! Welcome to Nullspace!</span></html>",
        "Nullspace?",
        "What is this place? How did I get here?",
        "<html><span style=color:'yellow';>You’re here to fix things, obviously. You’re the one who clicked “Yes,” right?</span></html>",
        "Fix what? I don’t even know where “here” is.",
        "<html><span style=color:'yellow';>You’re in Nullspace, dummy. It’s all messed up, and you’ve gotta help fix it.</span></html>",
        "<html><i>This is insane. I must be dreaming.</i></html>",
        "<html><i>She looks around at the strange, glitching environment.</i></html>",
        "Okay, fine. What do I have to do?",
        "<html><span style=color:'yellow';>Well, first, you’ve got to figure out how to get back to the real world.</span></html>",
        "<html><span style=color:'yellow';>But that’s gonna take more than just fixing bugs.</span></html>",
        "<html><span style=color:'yellow';>You’ll need to fix... well, you...</span></html>",
        "Great. Just what I needed.",
        "", //1 Raina
        "<html><b span style=color:#ed4337;>MEMORY LEAK.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>A soft, steady breath from Elara fills the silence.</i></html>",
        "Okay, Elara, pull yourself together. This is just... some weird glitch in the matrix.",
        "<html><i>A soft buzzing sound fills the air. Elara blinks, and the scene shifts to reveal a fractured, digital world.</i></html>",
        "This is not a dream. This is... definitely not a dream.",
        "<html><i>Lines of code float in the air like constellations.</i></html>",
        "<html><i>The ground beneath her is unstable, flickering between solid and transparent.</i></html>",
        "<html><span style=color:'yellow';>You’re getting the hang of it!</span></html>",
        "Jeez! Don’t sneak up on me like that!",
        "<html><span style=color:'yellow';>Sorry, I get excited. Anyway, welcome to the first level of Nullspace.</span><html>",
        "<html><span style=color:'yellow';>This place is full of glitches, and you’re gonna have to clean them up.</span></html>",
        "Glitches? What do you mean?",
        "<html><span style=color:'yellow';>See that over there?</span></html>",
        "<html><i>Byte points to a nearby structure that’s glitching in and out of existence, flickering between code and broken pixels.</i></html>",
        "Yeah, I see it. What is it?",
        "<html><span style=color:'yellow';>That’s a Memory Glitch. It’s a part of you, something you’ve been avoiding.</span></html>",
        "<html><span style=color:'yellow';>Fix it, and maybe you’ll start to understand this whole mess..</span></html>",
        "Avoiding? What does that even mean?",
        "<html><i>Elara walks toward the glitching structure.</i></html>",
        "<html><i>As she gets closer, the glitch intensifies, and distorted memories begin to flood her mind; flashes of a heated argument with Raina, her best friend, who she hasn’t spoken to in months.</i></html>",
        "I... I haven’t thought about this in so long.",
        "<html><i>The glitch pulses.</i></html>",
        "<html><i>A voice echoes in her mind, faint but clear.</i></html>",
        "<html><b span style=color:'red';>Why are you always shutting me out, Elara?</span></html>",
        "<html><b span style=color:'red';>I’m here, you know... but you never seem to care anymore.</span></html>",
        "I... I didn’t mean to...",
        "<html><i>The glitch intensifies, and Elara reaches out, touching it.</i></html>",
        "<html><i>The distortion stops, and the glitch begins to stabilize, revealing a clear image of Raina’s face, frozen in time.</i></html>",
        "<html><i>But it’s not just her face; it’s the way she looked the last time they spoke, hurt and confused.</i></html>",
        "That night... I should’ve said something.",
        "<html><i>The memory of that night floods back; her avoiding Raina’s calls, brushing off her concerns, telling herself that it was easier to just let things fade away.</i></html>",
        "I thought if I just kept going, kept busy, it would all fix itself.",
        "But it didn’t.",
        "<html><i>She stares at the image of Raina, the weight of regret heavy in her chest.</i></html>",
        "<html><span style=color:'yellow';>You did it. You fixed the glitch.</span></html>",
        "<html><span style=color:'yellow';>But it’s not over.</span></html>",
        "That was... real.",
        "I didn’t even realize how much I’ve been avoiding it.",
        "<html><span style=color:'yellow';>It’s all connected.</span></html>",
        "<html><span style=color:'yellow';>The glitches aren’t just in the system; they’re in you.</span></html>",
        "I’ve been running from this for so long...",
        "<html><span style=color:'yellow';>You can’t fix the system without fixing yourself. But don’t worry, we’ll figure it out together.</span></html>",
        "<html><i>Elara takes a deep breath, looking at the now-stable image of Raina.</i></html>",
        "I don’t know what this place is or why I’m here.",
        "But maybe... maybe I’ve been avoiding more than just bugs.",
        "", //2 Grandma
        "<html><b span style=color:#ed4337;>CODE RED.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The soft hum of the laptop fills the silence.</i></html>",
        "<html><i>Elara’s breathing slows, the weight of her thoughts pressing in.</i></html>",
        "I thought I was too busy to care. Too busy to notice.",
        "But... maybe I wasn’t as busy as I thought.",
        "Maybe I was just... avoiding everything that made me uncomfortable.",
        "<html><i>The screen flickers, and the next glitch appears; a soft, glowing figure in the distance.</i></html>",
        "<html><i>It looks familiar, but Elara can’t quite place it.</i></html>",
        "<html><i>She walks toward it, the glitch growing clearer with each step.</i></html>",
        "This one... feels different. It’s not like the others.",
        "<html><i>As Elara gets closer, the glitch clears up, revealing an image of an older woman; her grandmother, sitting in a cozy chair by a window, knitting a scarf.</i></html>",
        "<html><i>The image is warm, soft, almost like a memory Elara had forgotten.</i></html>",
        "Grandma...?",
        "<html><i>The image flickers again, and Elara sees a memory play out.</i></html>",
        "<html><i>Her grandmother is sitting at the kitchen table, a gentle smile on her face, while Elara, much younger, rolls her eyes and sighs as her grandmother insists on packing her lunch for school.</i></html>",
        "<html><b span style=color:'red';>You’re going to need something to eat, Elara. You can’t skip meals, sweetheart</span></html>",
        "<html><b span style=color:'red';>I’m fine, Grandma. I’m not a kid anymore. I can handle it.</span></html>",
        "<html><i>The memory shifts to another moment; her grandmother fussing over Elara’s jacket on a cold winter day, adjusting the collar, making sure it’s zipped up all the way.</i></html>",
        "<html><b span style=color:'red';>Make sure you stay warm, dear. You don’t want to catch a cold.</span></html>",
        "<html><b span style=color:'red';>I’m fine! Stop treating me like a baby.</span></html>",
        "<html><i>The image of her grandmother flickers again, and Elara’s heart sinks.</i></html>",
        "<html><i>She remembers the last time they spoke, the last time she saw her; just before her grandmother passed away.</i></html>",
        "I never told her how much I appreciated her. How much I needed her.",
        "<html><i>The image shifts again, showing her grandmother lying in her bed, frail and weak.</i></html>",
        "<html><i>Elara is standing by her arm, arms crossed, unable to face her.</i></html>",
        "<html><b span style=color:'red';>Don’t be mad at me, Elara. I only wanted to see you succeed... to make sure you will be okay.</span></html>",
        "<html><i>Elara’s younger self just stands there, silent, unable to speak the words she should have said.</i></html>",
        "<html><i>The memory fades, and the glitch stabilizes, leaving Elara staring at her grandmother’s warm, loving face.</i></html>",
        "I didn’t know.",
        "I didn’t understand how much she loved me.",
        "How much she just wanted to keep me safe...",
        "<html><i>She closes her eyes, a tear slipping down her cheek.</i></html>",
        "I resented her for trying to protect me... for caring too much.",
        "But now... now I’d give anything to go back.",
        "To tell her I understood. To thank her.",
        "<html><i>The glitch flickers one last time, and the image of her grandmother disappears, leaving Elara standing alone in the quiet, digital space.</i></html>",
        "<html><span style=color:'yellow';>You fixed another one. But this one... this one’s a little harder, huh?</span></html>",
        "Yeah. I didn’t even realize... how much I took for granted.",
        "<html><span style=color:'yellow';>It’s not easy. But you’re getting there.</span></html>",
        "I always thought I had time.",
        "But time... time doesn’t wait for anyone.",
        "", //3 Dream
        "<html><b span style=color:#ed4337;>SEGMENTATION FAULT.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The faint hum of the laptop continues, accompanied by the rhythmic ticking of a clock.</i></html>",
        "<html><i>Elara’s gaze drifts to the corner of the screen, where a new glitch begins to form; a swirling, fragmented map of the world.</i></html>",
        "This one feels... bigger.",
        "Like it’s pulling me somewhere far away.",
        "<html><i>The glitch stabilizes, and Elara finds herself standing in a grand hall.</i></html>",
        "<html><i>The walls are lined with flags from different countries, their colors vibrant and striking.</i></html>",
        "<html><i>At the center of the room is a podium, a microphone, and an empty chair.</i></html>",
        "<html><i>The air feels heavy with expectation.</i></html>",
        "I know this place. It’s not real, but... it’s familiar.",
        "<html><i>As she steps closer to the podium, the scene shifts.</i></html>",
        "<html><i>Suddenly, she’s younger, sitting at her childhood desk, surrounded by stacks of books and a world map pinned to the wall.</i></html>",
        "<html><i>She’s practicing a speech in front of a mirror, her voice shaky but determined.</i></html>",
        "<html><b span style=color:'red';>Good evening, esteemed delegates.</span></html>",
        "<html><b span style=color:'red';>Today, we gather to discuss a matter of global importance...</span></html>",
        "<html><i>The memory flickers, and the younger Elara looks up, her eyes shining with ambition.</i></html>",
        "<html><b span style=color:'red';>One day, I’ll be there. I’ll make a difference.</span></html>",
        "<html><i>The scene shifts again.</i></html>",
        "<html><i>Now, Elara is older, sitting in a college lecture hall.</i></html>",
        "<html><i>She’s scribbling notes furiously, her passion still burning bright.</i></html>",
        "<html><i>But the memory grows hazy, and the scene changes once more; this time, to a dimly lit room where Elara sits in front of her laptop, staring at a blank application form for a diplomatic internship.</i></html>",
        "I remember this. I couldn’t even fill out the first question",
        "<html><i>The younger Elara in the memory hesitates, her fingers hovering over the keyboard.</i></html>",
        "<html><i>She looks frustrated, then closes the laptop with a sigh.</i></html>",
        "<html><b span style=color:'red';>Maybe I’m not good enough.</span></html>",
        "<html><i>The scene fades, leaving Elara standing alone in the grand hall again.</i></html>",
        "<html><i>The flags now look faded, the podium dusty and forgotten.</i></html>",
        "I told myself it was just a silly dream.",
        "That I wasn’t smart enough, brave enough...",
        "But was it really about that? Or was I just scared?",
        "<html><i>A voice echoes softly in the hall; it’s her own, but older, more worn.</i></html>",
        "<html><b span style=color:'red';>You gave up before you even tried.</span></html>",
        "<html><i>Elara flinches, the words hitting her like a punch to the gut.</i></html>",
        "<html><i>She looks up at the empty chair by the podium, imagining herself sitting there, speaking to the world.</i></html>",
        "I wanted to be someone who mattered. Someone who could change things.",
        "But instead, I stayed in my bubble, too afraid to fail.",
        "<html><i>She takes a deep breath, her hands trembling.</i></html>",
        "It’s not too late. It can’t be.",
        "<html><i>The glitch begins to fade, the map reassembling itself into a complete image.</i></html>",
        "<html><i> Elara reaches out, touching it gently.</i></html>",
        "<html><span style=color:'yellow';>That one hit a nerve, huh?</span></html>",
        "Yeah. I guess I forgot how much I wanted it... how much it meant to me.",
        "<html><span style=color:'yellow';>Forgotten doesn’t mean gone.</span></html>",
        "Maybe I don’t have to give up.",
        "Maybe... it’s time to try again.",
        "", //4 Breakup
        "<html><b span style=color:#ed4337;>STACK OVERFLOW.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The familiar hum of the laptop returns, accompanied by the faint sound of breaking glass.</i></html>",
        "<html><i>Elara glances at the screen, where a glitch begins to spread like a spiderweb crack.</i></html>",
        "<html><i>She hesitates, her hand hovering over the keyboard.</i></html>",
        "This one feels... different.",
        "<html><i>The glitch pulls her in, and she finds herself in a cozy apartment.</i></html>",
        "<html><i>The room is filled with warmth; soft lighting, scattered books, and the faint smell of coffee.</i></html>",
        "<html><i>On the couch sits someone she knows all too well.</i></html>",
        "<html><i>Their face is blurry, but their voice is unmistakable.</i></html>",
        "<html><b span style=color:'red';>You never really saw me, did you?</span></html>",
        "<html><i>Elara freezes, her chest tightening.</i></html>",
        "<html><i>The scene shifts, showing her younger self laughing with the person in a coffee shop.</i></html>",
        "<html><i>They’re leaning in close, sharing stories.</i></html>",
        "We were happy. Weren’t we?",
        "<html><i>The memory flickers, replaced by another.</i></html>",
        "<html><i>This time, they’re sitting in silence, the air between them heavy.</i></html>",
        "<html><i>The person looks at Elara, their eyes filled with something she can’t quite place; disappointment? Hurt? </i></html>",
        "<html><b span style=color:'red';>I just wanted to be part of your world.</span></html>",
        "<html><i>The scene shifts again, showing Elara at her desk, engrossed in her work.</i></html>",
        "<html><i>The person stands in the doorway, watching her, then quietly leaves.</i></html>",
        "<html><i>Elara doesn’t notice.</i></html>",
        "I thought I was doing the right thing.",
        "Focusing on my goals, building a future.",
        "<html><i>The glitch intensifies, showing fragments of arguments; raised voices, slammed doors, words that can’t be taken back.</i></html>",
        "<html><b span style=color:'red';>You stopped trying. You stopped caring.</span></html>",
        "<html><i>Elara clenches her fists, her voice trembling.</i></html>",
        "I didn’t stop caring.",
        "I just... didn’t know how to show it.",
        "<html><i>The scene shifts one last time, showing the moment they broke up.</i></html>",
        "<html><i>The person is packing a bag, their movements slow and deliberate.</i></html>",
        "<html><i>Elara stands frozen, unable to find the words to stop them.</i></html>",
        "<html><b span style=color:'red';>I hope you find what you’re looking for, Elara. I really do.</span></html>",
        "<html><i>The door closes, leaving Elara alone.</i></html>",
        "<html><i>The memory fades, and she’s back in the apartment, now empty and cold.</i></html>",
        "I thought I was doing what I had to.",
        "But all I did was push them away.",
        "<html><i>A soft voice breaks the silence; it’s Byte, appearing beside her.</i></html>",
        "<html><span style=color:'yellow';>Regret’s a tricky thing. It sticks to you like glue.</span></html>",
        "I didn’t mean to hurt them. I just...",
        "I didn’t know how to balance everything.",
        "<html><span style=color:'yellow';>Maybe it’s not about balance.</span></html>",
        "<html><span style=color:'yellow';>Maybe it’s about learning to let people in, even when it’s messy.</span></html>",
        "<html><i>Elara looks around the empty room, her eyes stinging with unshed tears.</i></html>",
        "I wish I could tell them that now.",
        "<html><span style=color:'yellow';>You can’t change the past.</span></html>",
        "<html><span style=color:'yellow';>But you can learn from it.</span></html>",
        "<html><i>The glitch begins to fade, leaving Elara standing in the middle of the empty room.</i></html>",
        "<html><i>She takes a deep breath, her voice steady but soft.</i></html>",
        "I’ll do better.",
        "Next time, I’ll do better.",
        "", //5 Friends
        "<html><b span style=color:#ed4337;>INFINITE LOOP.</b></html>",
        "<html><i>Black screen.</i></html>",
        "<html><i>The hum of the laptop feels unsteady, like a song out of tune.</i></html>",
        "<html><i>The glitch appears again, this time more jagged, its edges sharp and flickering.</i></html>",
        "<html><i>Elara hesitates before reaching out.</i></html>",
        "<html><i>The moment her fingers touch the keys, she’s pulled into the past.</i></html>",
        "<html><i>The scene opens in a bright, bustling arcade. Laughter echoes, neon lights flash, and the sound of coins clinking fills the air.</i></html>",
        "<html><i>Elara stands in the middle of it all, watching her younger self and her old friend group crowded around a claw machine.</i></html>",
        "This was our spot. Every Friday after class.",
        "<html><i>The memory comes to life; her friends cheering as one of them wins a stuffed bear.</i></html>",
        "<html><i>A younger Elara hugs the winner, their laughter blending with the chaos around them.</i></html>",
        "<html><i>The warmth of the moment is almost overwhelming.</i></html>",
        "<html><b span style=color:'red';>Okay, okay, my turn! Watch and learn!</span></html>",
        "<html><i>The scene shifts, the arcade fading into a quiet park.</i></html>",
        "<html><i>The group is sprawled on a blanket under the stars, their voices softer now.</i></html>",
        "<html><b span style=color:'red';>Do you think we’ll always be like this? Together?</span></html>",
        "<html><i>Elara watches as her younger self grins, her voice confident.</i></html>",
        "<html><b span style=color:'red';>Of course. Nothing’s going to change.</span></html>",
        "<html><i>The memory fractures, the warmth replaced by a cold, empty feeling.</i></html>",
        "<html><i>The group is smaller now; just Elara and one other friend. The others are gone, their absence a silent ache.</i></html>",
        "<html><i>A faint echo of a funeral bell rings in the distance.</i></html>",
        "We lost him. And everything changed.",
        "<html><i>The glitch intensifies, showing fragments of arguments, misunderstandings, and quiet goodbyes.</i></html>",
        "<html><i>The friend who stayed is always there, always reaching out, but Elara pulls away, her fear of losing them too much to bear.</i></html>",
        "<html><b span style=color:'red';>I’m still here, Elara. Why won’t you let me in?</span></html>",
        "<html><i>Elara’s chest tightens as the memory shifts to a coffee shop.</i></html>",
        "<html><i>Her friend sits across from her, their expression weary but hopeful.</i></html>",
        "<html>span style=color:'red';>You don’t have to do this alone, you know.</span></html>",
        "<html><i>Younger Elara looks away, her voice clipped.</i></html>",
        "<html><b span style=color:'red';>I’m fine. Really.</span></html>",
        "<html><i>The scene fades, leaving Elara standing in the empty arcade. The claw machine is still there, but the lights are dim, the laughter gone.</i></html>",
        "<html><i>Byte appears beside her, their tone unusually gentle.</i></html>",
        "<html><span style=color:'yellow';>You miss them, don’t you?</span></html>",
        "Every day.",
        "<html><span style=color:'yellow';>But you’re so focused on what you’ve lost, you’re forgetting what you still have.</span></html>",
        "<html><i>Elara’s gaze shifts to the claw machine. The reflection in the glass shows her current self, older and heavier with regret.</i></html>",
        "I pushed them away because I was scared. I didn’t want to lose anyone else.",
        "<html><span style=color:'yellow';>And in doing that, you lost them anyway.</span></html>",
        "<html><i>The weight of Byte’s words settles over her.</i></html>",
        "<html><i>She closes her eyes, the memories swirling around her like a storm.</i></html>",
        "I don’t want to keep running from this.",
        "<html><span style=color:'yellow';>Then stop. Reach out. The past isn’t coming back, but the present is still here.</span></html>",
        "", //6 Reflection
    };
}
